#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/eurovision-by-vincent:latest@sha256:dd3e6af4eb8a10721e5281874af91f0ae2489053bf0cde6e8f3d565053b2f59f
    restart: on-failure:5
    environment:
      - PORT=3000
      - TOKENS=${TOKENS}
    ports:
      - "3017:3000"
