#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/eurovision-by-vincent:latest@sha256:8b60d489982dbfc19df2e421b39a2ff3e1caff83cf7edc1bfac80d10359e0e49
    restart: on-failure:5
    environment:
      - PORT=3000
      - TOKENS=${TOKENS}
    ports:
      - "3017:3000"
