#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/eurovision-by-vincent:latest
    restart: on-failure:5
    environment:
      - PORT=3000
      - TOKENS=${TOKENS}
    ports:
      - "3017:3000"
